name: Build and Test
# only style tests

on:
  push:
    paths:
      - 'src/my_code.py'

jobs:

  Style_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint student program
      id: style
      continue-on-error: true
      run: |
        flake8 src/my_code >> .github/ISSUE_TEMPLATE/style-issues.md

    - name: Style fail message
      if: steps.style.outcome == 'failure'
      uses: machine-learning-apps/pr-comment@1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: .github/ISSUE_TEMPLATE/style-issues.md

    - name: Success message
      if: steps.style.outcome == 'success'
      uses: machine-learning-apps/pr-comment@1.0.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        path: .github/ISSUE_TEMPLATE/test-success.md
